include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_local_variable: error
    unused_import: error
    invalid_annotation_target: error
    missing_required_param: error
    dead_code: error

  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - avoid_print
