name: Flutter Android CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Java Environment
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup Flutter Environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      - name: Build Apk
        run: flutter build apk --release

